version: '2'
services:
  tomcat_myproj:
    build: tomcat
    image: tomcat_myproj
    ports:
      - 8080:8080
    links:
      - mysql:mysql_myproj
    depends_on:
      - mysql_myproj
  mysql_myproj:
     build: mysql
     image: mysql_myproj
     environment:
       - MYSQL_ROOT_PASSWORD=123456
     ports:
        - 3306:3306
