version: "2"
services:
  app:
    context: ${pwd}
    build: tomcat
    container_name: app
    depends_on:
      - redis
      - db
    ports:
      - 8080:8080
    volumes:
      - ${my_proj}/ROOT:/usr/local/tomcat/webapps/ROOT

  redis:
    context: ${pwd}
    build: redis
    container_name: redis
    ports:
      - 6379:6379     
    volumes:
      - ${my_proj}/data:/data

  db:
    context: ${pwd}
    build: mysql
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - ${my_proj}/data:/var/lib/mysql
      - ${my_proj}/conf:/etc/mysql/conf.d 
    environment:
      - MYSQL_ROOT_PASSWORD:'123456' 